site_name: atpbar
repo_url: https://github.com/alphatwirl/atpbar
repo_name: alphatwirl/atpbar
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: fontawesome/solid/bars
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    # - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Quick Start: quick.md
  - User Guide:
      - guide/index.md
      - concurrent.futures:
        - ThreadPoolExecutor: guide/ThreadPoolExecutor.md
        - ProcessPoolExecutor: guide/ProcessPoolExecutor.md
      - threading.Thread: guide/threading.md
      - multiprocessing:
        - Process: guide/multiprocessing.md
        - Pool: guide/multiprocessing.Pool.md
      - Disabling progress bars: guide/disable.md
  - Features:
      - features/index.md
      - break and exception: features/break-exception.md
      - combination: features/combination.md
      - Jupyter: features/jupyter.md
      - Non TTY: features/non-tty.md
