name: Check static types

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: type-check-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install packages
        run: |
          pip install --upgrade pip
          pip install -e '.[tests,jupyter]'
          pip install --upgrade mypy

      - name: Run mypy
        run: mypy --show-traceback atpbar/ tests/
