name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        jupyter: ["true", "false"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        env:
          JUPYTER: ${{ matrix.jupyter }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[tests]'
          if "$JUPYTER"; then
            python -m pip install -e '.[jupyter]';
          fi
          python -m pip list
      - name: Test with pytest
        run: |
          pytest -vv --cov --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true
